/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as AuthenticatedPrintingsRouteImport } from './routes/_authenticated/printings'
import { Route as AuthenticatedSearchCardsRouteImport } from './routes/_authenticated/searchCards'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated/storage'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedCardDetailsCardIdRouteImport } from './routes/_authenticated/cardDetails.$cardId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintingsRoute = AuthenticatedPrintingsRouteImport.update({
  id: '/printings',
  path: '/printings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchCardsRoute =
  AuthenticatedSearchCardsRouteImport.update({
    id: '/searchCards',
    path: '/searchCards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCardDetailsCardIdRoute =
  AuthenticatedCardDetailsCardIdRouteImport.update({
    id: '/cardDetails/$cardId',
    path: '/cardDetails/$cardId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/printings': typeof AuthenticatedPrintingsRoute
  '/searchCards': typeof AuthenticatedSearchCardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/cardDetails/$cardId': typeof AuthenticatedCardDetailsCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/printings': typeof AuthenticatedPrintingsRoute
  '/searchCards': typeof AuthenticatedSearchCardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/cardDetails/$cardId': typeof AuthenticatedCardDetailsCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/printings': typeof AuthenticatedPrintingsRoute
  '/_authenticated/searchCards': typeof AuthenticatedSearchCardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cardDetails/$cardId': typeof AuthenticatedCardDetailsCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/cards'
    | '/collection'
    | '/printings'
    | '/searchCards'
    | '/settings'
    | '/storage'
    | '/transactions'
    | '/cardDetails/$cardId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/cards'
    | '/collection'
    | '/printings'
    | '/searchCards'
    | '/settings'
    | '/storage'
    | '/transactions'
    | '/'
    | '/cardDetails/$cardId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/cards'
    | '/_authenticated/collection'
    | '/_authenticated/printings'
    | '/_authenticated/searchCards'
    | '/_authenticated/settings'
    | '/_authenticated/storage'
    | '/_authenticated/transactions'
    | '/_authenticated/'
    | '/_authenticated/cardDetails/$cardId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printings': {
      id: '/_authenticated/printings'
      path: '/printings'
      fullPath: '/printings'
      preLoaderRoute: typeof AuthenticatedPrintingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/searchCards': {
      id: '/_authenticated/searchCards'
      path: '/searchCards'
      fullPath: '/searchCards'
      preLoaderRoute: typeof AuthenticatedSearchCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cardDetails/$cardId': {
      id: '/_authenticated/cardDetails/$cardId'
      path: '/cardDetails/$cardId'
      fullPath: '/cardDetails/$cardId'
      preLoaderRoute: typeof AuthenticatedCardDetailsCardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedPrintingsRoute: typeof AuthenticatedPrintingsRoute
  AuthenticatedSearchCardsRoute: typeof AuthenticatedSearchCardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCardDetailsCardIdRoute: typeof AuthenticatedCardDetailsCardIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedPrintingsRoute: AuthenticatedPrintingsRoute,
  AuthenticatedSearchCardsRoute: AuthenticatedSearchCardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCardDetailsCardIdRoute: AuthenticatedCardDetailsCardIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
